language: cpp
os:
  - linux
  - osx

dist: trusty
sudo: false

addons:
  apt:
   packages:
    - libboost-dev
    - libboost-thread-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libicu-dev
    - maven

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost icu4c maven; fi

script:
 - mkdir build
 - cd build/
 - cmake ..
 - make
 - cd ../
 - mvn test
