language: cpp
os:
  - linux
  - osx

addons:
  apt:
   packages:
    - libboost-dev
    - libicu-dev

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install icu4c ; fi

script:
 - mkdir build
 - cd build/
 - cmake ..
 - make
