language: java

env:
  # if explicitly set, instead of compiling graphANNIS, the released version will be used 
  - GRAPHANNIS_VERSION=v0.11.1 RUST_VERSION=1.30.0
  #- RUST_VERSION=1.30.0

branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - test-release-tag-please-ignore
  - develop

before_install:
  - "curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=$RUST_VERSION -y"
  - export PATH=$HOME/.cargo/bin:$PATH
  # checkout latest development version of graphANNIS
  - ./misc/get-graphannis.sh

cache: 
  directories:
  - $HOME/.cargo
  - $HOME/.m2



script:
  - mvn test -B
