language: java

env:
  # if explicitly set, instead of compiling graphANNIS, the released version will be used 
  #- GRAPHANNIS_VERSION=v0.7.1
  - RUST_VERSION=1.28.0

before_install:
  - "curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=$RUST_VERSION -y"
  - export PATH=$HOME/.cargo/bin:$PATH
  # checkout latest development version of graphANNIS
  - ./misc/get-graphannis.sh

cache: cargo



script:
  - mvn test -B