language: java

jdk:
   - openjdk8

env:
  # if explicitly set, instead of compiling graphANNIS, the released version will be used 
  #- GRAPHANNIS_VERSION=v0.13.0

branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - develop
  - feature/p2-site
  
cache: 
   directories:
   - $TRAVIS_HOME/.cache/sccache
   - $TRAVIS_HOME/.cargo/
   - $TRAVIS_HOME/.rustup/
   - ext/graphANNIS/target
   
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

before_install:
  - "curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain stable -y"
  - export PATH=$HOME/.cargo/bin:$PATH
  # checkout latest development version of graphANNIS
  - ./misc/get-graphannis.sh
  
before_script:
   - export SHORT_VERSION=`echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'`

script:
  - mvn test -B
  
before_deploy:
   - mvn p2:site

deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-p2.sh
    on:
      repo: korpling/graphANNIS-java
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-p2.sh
    on:
      repo: korpling/graphANNIS-java
      branch: feature/p2-site
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
        
    