name: Deploy graphANNIS-java release
on: push

jobs:
  p2:
    name: Deploy as P2 repository
    # Only run Job on tagged commits that start with "v"
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
      - run: 'mvn install p2:site'
      - run: 'misc/deploy-p2.sh'
        env:
            SHORT_VERSION: echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'
