name: Deploy graphANNIS-java release
on: push

jobs:
  p2:
    name: Deploy as P2 repository
    # Only run Job on tagged commits that start with "v"
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
      - name: Set SHORT_VERSION environment variable
        run: echo "SHORT_VERSION=$(echo ${GITHUB_REF:-refs/heads/develop} | sed -E 's/^(refs/heads/develop).*(\.[0-9]+)$/$2/')" >> $GITHUB_ENV
      - run: 'mvn install p2:site'
      - run: 'misc/deploy-p2.sh'
