name: Deploy graphANNIS-java release
on: push

jobs:
  p2:
    name: Deploy as P2 repository
    # Only run Job on tagged commits that start with "v"
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    steps:
      - run: 'mvn p2:site'
      - run: 'misc/deploy-p2.sh'
        with:
            GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
            SHORT_VERSION: echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'
