name: Automated tests
on: push

jobs:
  test:
    name: Execute all automated tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set JAVA_HOME to included JDK 8
        run: echo JAVA_HOME=$JAVA_HOME_8_X64 >> $GITHUB_ENV
      - name: Run Maven install (includes tests)
        run: mvn install
