name: Automated tests
on: push

jobs:
  test:
    name: Execute all automated tests
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
          java-version: '8'
          java-package: jdk
    - name: Run Maven test
      run: mvn test
