name: Automated tests
on: push

jobs:
  test_ubuntu:
    name: Execute all automated tests on Ubuntu Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set JAVA_HOME to included JDK 8
        run: echo JAVA_HOME=$JAVA_HOME_8_X64 >> $GITHUB_ENV
      - name: Run Maven install (includes tests)
        run: mvn install
  test_windows:
    name: Execute all automated tests on Windows
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven install (includes tests)
        run: mvn install
  test_mac:
    name: Execute all automated tests on OSX
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set JAVA_HOME to included JDK 8
        run: echo JAVA_HOME=$JAVA_HOME_8_X64 >> $GITHUB_ENV
      - name: Run Maven install (includes tests)
        run: mvn install